---
output: github_document
---

### Presentaciones // Presentations

En este repositorio voy subiendo presentaciones que he realizado, de tal forma de poder compartirlas con la audiencia. Cada una menciona la fecha de realizaci칩n, el evento y el idioma en el que se encuentra (ingl칠s o espa침ol).   
In this repository, I am uploading some of my presentations to be share with the audience. Each one included: date, event and language (english or spanish).

#### Sesi칩n RLadies Chile: Club de Lectura "Data Feminism" (cap칤tulo 3).
Sesi칩n realizada el 29 de Julio, 2021.Organizado por la colaboraci칩n de RLadies Santiago, Valapara칤so, Talca, Concepci칩n. 
Idioma (language): Espa침ol (Spanish).
 
游눹 [Project Presentation](pdf/20210729datafeminism_3.pdf "Project Presentation PDF")

#### Session Workshop of Sociology: Writing a PhD and how to organize academic events.
Sesi칩n realizada el 17 de noviembre, 2021.Organizado el Departamento de Sociolog칤a, de la Universidad de Manchester. 
Session of the 17th of november, 2021. Workshop of Sociology, University of Manchester. 

Idioma (language): Ingles (English).
 
游눹 [Project Presentation](pdf/2021117workshopsocphd_uk.pdf "Project Presentation PDF")

#### Workshop Encuentro Ciencia y Tecnolog칤a: "Introducci칩n al An치lisis de Redes Sociales".
Sesi칩n realizada el 11 de enero, 2022.Organizado por la Red Chilena de Ciencia y Tencolog칤a. 
Session of the 11th of january, 2022. Workshop organized by the Chilean Network of Science and Technology.

Idioma (language): Espa침ol (Spanish).

游눹 [Project Presentation](pdf/20220111workshop_introsna.pdf "Project Presentation PDF")

#### Para contactarme // Contact information:
游꺝 [Twitter](https://twitter.com/FranciscaOrtizR)
游닒 Email: franortizruiz@gmail.com
